### ISSUE TITLE
Rosetta run error

### ISSUE THREAD

**Issue by jerry1gotobed** [JinyuanSun/Codes_for_FoldX#17]

**Comment by jerry1gotobed** [comment]
The full output:

/bin/sh: 1: relax.static.linuxgccrelease: not found
[INFO]: Rosetta Relax took 0.008716 seconds.
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory

ERROR: Cannot open file "1PGA_0001.pdb"
ERROR:: Exit from: src/core/import_pose/import_pose.cc line: 362

[ ERROR ]: Caught exception:


File: src/core/import_pose/import_pose.cc:362
[ ERROR ] UtilityExitException
ERROR: Cannot open file "1PGA_0001.pdb"

AN INTERNAL ERROR HAS OCCURED. PLEASE SEE THE CONTENTS OF ROSETTA_CRASH.log FOR DETAILS.


[DEBUG]: Rosetta mutation T_2_E took 2.286808 seconds.
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
[DEBUG]: Rosetta mutation T_2_P took 2.355683 seconds.
[DEBUG]: Rosetta mutation M_1_A took 2.428909 seconds.
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
cp: cannot stat '../../rosetta_relax/1PGA_0001.pdb': No such file or directory
[DEBUG]: Rosetta mutation M_1_I took 2.535999 seconds.

ERROR: Cannot open file "1PGA_0001.pdb"
ERROR:: Exit from: src/core/import_pose/import_pose.cc line: 362

[ ERROR ]: Caught exception:


File: src/core/import_pose/import_pose.cc:362
[ ERROR ] UtilityExitException
ERROR: Cannot open file "1PGA_0001.pdb"

...............

[DEBUG]: Rosetta mutation Y_3_S took 2.427436 seconds.
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/DDGScan-0.1.0-py3.9.egg/utils/rosetta.py", line 435, in run_row1
    result = rosetta_binder.read_ddg_monomer_out(
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/DDGScan-0.1.0-py3.9.egg/utils/rosetta.py", line 325, in read_ddg_monomer_out
    ddg = float(open(ddg_monomer_file, "r").readlines()[1].split()[2])
FileNotFoundError: [Errno 2] No such file or directory: 'ddg_predictions.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniforge3/envs/ddgscan/bin/DDGScan", line 4, in <module>
    __import__('pkg_resources').run_script('DDGScan==0.1.0', 'DDGScan')
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/pkg_resources/__init__.py", line 755, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1744, in run_script
    exec(script_code, namespace, namespace)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/DDGScan-0.1.0-py3.9.egg/EGG-INFO/scripts/DDGScan", line 222, in <module>
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/DDGScan-0.1.0-py3.9.egg/utils/grape_phaseI.py", line 716, in main1
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/DDGScan-0.1.0-py3.9.egg/utils/grape_phaseI.py", line 154, in run_ddg_monomer
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "/root/miniforge3/envs/ddgscan/lib/python3.9/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
FileNotFoundError: [Errno 2] No such file or directory: 'ddg_predictions.out'

**Comment by jerry1gotobed** [comment]
Rosetta Crash log

##############################################################################################################
#
# Rosetta crash log. Please submit the contents of this file to http://crash.rosettacommons.org/
# or use the script Rosetta/main/source/scripts/python/public/report_crashes.py
#

[START_CRASH_REPORT]
[ROSETTA_VERSION]: 2021.16+release.8ee4f02
[COMMIT_DATE]: 2021-04-20T20:57:38.289184
[APPLICATION]: /root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease
[MODE]: Release
[EXTRAS]: mpi (OpenMPI 4.1.5) 
[OS]: GNU/Linux
[COMPILER]: GCC version "9.4.0"
[STDLIB]: libstdc++ version 20210601
[START_OPTIONS]
 -in:path:database=/root/rosetta/rosetta_src_2021.16.61629_bundle/main/database/ -in:file:s=1PGA_0001.pdb -packing:use_input_sc -ddg:min_cst=false -ddg:local_opt_only -ddg:mean=false -ddg:min -ddg:sc_min_only=false -ddg:opt_radius=0.1 -ddg:mut_file=mtfile -ddg:iterations=1 -ddg:weight_file=soft_rep_design

[END_OPTIONS]

[START_BACKTRACE]: RAW_LIBC
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(backtrace_string[abi:cxx11](int)+0x43) [0x7f726b3b4b53]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::excn::Exception::Exception(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe3) [0x7f726b3eba03]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::UtilityExitException::UtilityExitException(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xfb) [0x7f726b3b8fbb]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::exit(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x37) [0x7f726b3b8c27]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.6.so(core::import_pose::pose_from_file(core::pose::Pose&, core::chemical::ResidueTypeSet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, core::import_pose::ImportPoseOptions const&, bool, core::import_pose::FileType)+0x52f) [0x7f7270cf9cef]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.6.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, core::import_pose::ImportPoseOptions const&, bool, core::import_pose::FileType)+0xf5) [0x7f7270cff8a5]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.6.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, core::import_pose::FileType)+0x39) [0x7f7270cffa69]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease(+0xd42e) [0x564df95e942e]
/lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f7269c6324a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f7269c63305]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease(+0x11a3d) [0x564df95eda3d]

[END_BACKTRACE]

[FILE]: src/core/import_pose/import_pose.cc
[LINE]: 362
[START_MESSAGE]
[ ERROR ] UtilityExitException
ERROR: Cannot open file "1PGA_0001.pdb"
